### ISSUE TITLE
spect@24 breaks integration tests with subscribable-things

### ISSUE THREAD

**Issue by chrisguttandin** [spectjs/spect#263]
Hi @dy,

I just noticed that upgrading spect to v24 breaks the integration tests of subscribable-things. I tried to find any documentation on what I need to update/change to make it work again but I couldn't find any.

Could you please let me know what I need to do?

**Comment by dy** [comment]
Hi Chris!
Sure, sorry for bothering.
Just replace `spect/v` with `value-ref` and `spect/h` with `hyperf`.
I'll add update guide.

Also check out https://github.com/spectjs/templize - it allows streaming reactive values directly to html

**Comment by chrisguttandin** [comment]
Thanks for your help and the quick reply. I made an attempt to update the dependencies here: https://github.com/chrisguttandin/subscribable-things/commit/98da621d6661c5e1d46f5f1942cda74c75642e07

Unfortunately I must be doing something wrong. It doesn't even build. :-(

**Comment by dy** [comment]
Right, it must be something to do with the way deps are included [here](https://npmfs.com/package/hyperf/1.1.1/src/index.js#L1)
```js
import htm from '../node_modules/htm/dist/htm.mjs'
import sube, { observable } from '../node_modules/sube/sube.js'
import swap from '../node_modules/swapdom/swap-inflate.js'
import { prop as attr } from '../node_modules/element-props/element-props.js'
```
You can include as `import h from 'hyperf/hyperf.js'` as workaround, I have to find out a way to import deps then.

**Comment by dy** [comment]
Ok, updated deps usage via import-maps. Just bump hyperf to 1.1.2.
Thanks for the report!

**Comment by chrisguttandin** [comment]
Thanks a lot, Dmitry.
